# Generated by Django 5.1.9 on 2026-03-25 02:04

import apps.members.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Family Account',
                'verbose_name_plural': 'Family Accounts',
            },
        ),
        migrations.CreateModel(
            name='MemberProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=200)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20)),
                ('join_date', models.DateField(auto_now_add=True)),
                ('waiver_signed', models.BooleanField(default=False)),
                ('waiver_signed_at', models.DateTimeField(blank=True, null=True)),
                ('loyalty_points', models.IntegerField(default=0)),
                ('referral_code', models.CharField(default=apps.members.models._default_referral_code, max_length=20, unique=True)),
                ('family_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='members.familyaccount')),
                ('primary_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_members', to='core.location')),
                ('referred_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='members.memberprofile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Member Profile',
                'verbose_name_plural': 'Member Profiles',
            },
        ),
        migrations.CreateModel(
            name='HealthProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fitness_goal', models.CharField(blank=True, max_length=100)),
                ('goal_detail', models.TextField(blank=True)),
                ('goal_timeline_weeks', models.IntegerField(blank=True, null=True)),
                ('activity_level', models.CharField(blank=True, max_length=50)),
                ('injuries_limitations', models.TextField(blank=True)),
                ('medical_conditions', models.TextField(blank=True)),
                ('medications', models.TextField(blank=True)),
                ('sleep_hours', models.FloatField(blank=True, null=True)),
                ('stress_level', models.CharField(blank=True, max_length=20)),
                ('dietary_preference', models.CharField(blank=True, max_length=50)),
                ('food_allergies', models.TextField(blank=True)),
                ('disliked_foods', models.TextField(blank=True)),
                ('current_supplements', models.TextField(blank=True)),
                ('typical_diet_description', models.TextField(blank=True)),
                ('water_intake_liters', models.FloatField(blank=True, null=True)),
                ('preferred_workout_time', models.CharField(blank=True, max_length=20)),
                ('prefers_group', models.BooleanField(default=False)),
                ('has_worked_with_trainer', models.BooleanField(default=False)),
                ('past_obstacles', models.TextField(blank=True)),
                ('intake_completed', models.BooleanField(default=False)),
                ('raw_intake_data', models.JSONField(default=dict)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='healthprofile', to='members.memberprofile')),
            ],
            options={
                'verbose_name': 'Health Profile',
                'verbose_name_plural': 'Health Profiles',
            },
        ),
        migrations.AddField(
            model_name='familyaccount',
            name='primary_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_primary', to='members.memberprofile'),
        ),
        migrations.CreateModel(
            name='BodyMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateField()),
                ('weight_kg', models.FloatField(blank=True, null=True)),
                ('body_fat_percent', models.FloatField(blank=True, null=True)),
                ('measurements', models.JSONField(default=dict)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='body_metrics', to='members.memberprofile')),
            ],
            options={
                'verbose_name': 'Body Metric',
                'verbose_name_plural': 'Body Metrics',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='NutritionRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('daily_calories', models.IntegerField(blank=True, null=True)),
                ('protein_g', models.IntegerField(blank=True, null=True)),
                ('carbs_g', models.IntegerField(blank=True, null=True)),
                ('fat_g', models.IntegerField(blank=True, null=True)),
                ('meal_plan', models.JSONField(default=dict)),
                ('nutritionist_reviewed', models.BooleanField(default=False)),
                ('nutritionist_notes', models.TextField(blank=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_recommendations', to='members.memberprofile')),
            ],
            options={
                'verbose_name': 'Nutrition Recommendation',
                'verbose_name_plural': 'Nutrition Recommendations',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplementRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('supplement_name', models.CharField(max_length=200)),
                ('reason', models.TextField()),
                ('suggested_dosage', models.CharField(max_length=100)),
                ('best_time_to_take', models.CharField(max_length=100)),
                ('member_already_takes', models.BooleanField(default=False)),
                ('professional_override', models.TextField(blank=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplement_recommendations', to='members.memberprofile')),
                ('override_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplement_overrides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Supplement Recommendation',
                'verbose_name_plural': 'Supplement Recommendations',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workout_date', models.DateField()),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(choices=[('ai', 'AI Recommended'), ('trainer', 'Trainer Plan'), ('manual', 'Manual')], max_length=20)),
                ('duration_minutes', models.IntegerField(blank=True, null=True)),
                ('exercises', models.JSONField(default=list)),
                ('mood_before', models.IntegerField(blank=True, null=True)),
                ('energy_after', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_logs', to='members.memberprofile')),
            ],
            options={
                'verbose_name': 'Workout Log',
                'verbose_name_plural': 'Workout Logs',
                'ordering': ['-workout_date', '-logged_at'],
            },
        ),
    ]
