# Generated by Django 5.1.9 on 2026-03-25 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='pin_hash',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
