# Generated by Django 5.1.9 on 2026-03-25 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_email', models.EmailField(db_index=True, max_length=254)),
                ('gym_schema', models.CharField(blank=True, db_index=True, max_length=100)),
                ('action', models.CharField(max_length=200)),
                ('target_model', models.CharField(blank=True, max_length=100)),
                ('target_id', models.IntegerField(blank=True, null=True)),
                ('details', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Audit Log Entry',
                'verbose_name_plural': 'Audit Log',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('max_members', models.IntegerField()),
                ('max_locations', models.IntegerField()),
                ('price_monthly', models.DecimalField(decimal_places=2, max_digits=8)),
                ('stripe_price_id', models.CharField(max_length=100)),
                ('features', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'GymForge Plan',
                'verbose_name_plural': 'GymForge Plans',
                'ordering': ['price_monthly'],
            },
        ),
    ]
