# Generated by Django 5.1.9 on 2026-03-25 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_description', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('stripe_payment_intent', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='completed', max_length=20)),
            ],
            options={
                'verbose_name': 'Card Purchase',
                'verbose_name_plural': 'Card Purchases',
                'ordering': ['-processed_at'],
            },
        ),
        migrations.CreateModel(
            name='MemberMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expiring', 'Expiring Soon'), ('overdue', 'Payment Overdue'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled'), ('frozen', 'Frozen')], db_index=True, default='active', max_length=20)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=100)),
                ('grace_period_days', models.IntegerField(default=3, help_text='Days after payment failure before status moves to suspended.')),
                ('overdue_since', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Member Membership',
                'verbose_name_plural': 'Member Memberships',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='MembershipTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('annual', 'Annual'), ('drop_in', 'Drop-in'), ('free', 'Free')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('trial_days', models.IntegerField(default=0)),
                ('cancellation_window_hours', models.IntegerField(default=2, help_text='How many hours before class start a member can cancel for free.')),
                ('no_show_fee', models.DecimalField(decimal_places=2, default=0.0, help_text='Charged immediately via Stripe when a member no-shows.', max_digits=6)),
                ('late_cancel_fee', models.DecimalField(decimal_places=2, default=0.0, help_text='Charged when a member cancels inside the cancellation window.', max_digits=6)),
            ],
            options={
                'verbose_name': 'Membership Tier',
                'verbose_name_plural': 'Membership Tiers',
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='MemberTab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('spending_limit', models.DecimalField(decimal_places=2, default=100.0, max_digits=8)),
                ('last_charged', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Member Tab',
                'verbose_name_plural': 'Member Tabs',
            },
        ),
        migrations.CreateModel(
            name='NoShowCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('charge_type', models.CharField(choices=[('no_show', 'No Show'), ('late_cancel', 'Late Cancel')], max_length=20)),
                ('stripe_payment_intent', models.CharField(blank=True, max_length=100)),
                ('charged_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='completed', max_length=20)),
            ],
            options={
                'verbose_name': 'No-Show Charge',
                'verbose_name_plural': 'No-Show Charges',
                'ordering': ['-charged_at'],
            },
        ),
    ]
