# Generated by Django 5.1.9 on 2026-03-25 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('checkin', '0001_initial'),
        ('core', '0001_initial'),
        ('members', '0001_initial'),
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardpurchase',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='checkin.membercard'),
        ),
        migrations.AddField(
            model_name='cardpurchase',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='checkin.doordevice'),
        ),
        migrations.AddField(
            model_name='membermembership',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='members.memberprofile'),
        ),
        migrations.AddField(
            model_name='membershiptier',
            name='included_services',
            field=models.ManyToManyField(blank=True, to='core.service'),
        ),
        migrations.AddField(
            model_name='membermembership',
            name='tier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='billing.membershiptier'),
        ),
        migrations.AddField(
            model_name='membertab',
            name='member',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tab', to='members.memberprofile'),
        ),
        migrations.AddField(
            model_name='noshowcharge',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='no_show_charges', to='scheduling.booking'),
        ),
        migrations.AddField(
            model_name='noshowcharge',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='no_show_charges', to='members.memberprofile'),
        ),
    ]
