# Generated by Django 5.1.9 on 2026-03-26 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membermembership',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
