# Generated by Django 5.1.9 on 2026-03-25 02:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BadgeMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('badge_type', models.CharField(choices=[('points', 'Total Points'), ('checkins', 'Total Check-ins'), ('workouts', 'Total Workouts'), ('streak', 'Day Streak'), ('referrals', 'Total Referrals'), ('custom', 'Custom')], default='points', max_length=20)),
                ('threshold', models.PositiveIntegerField(help_text='Value required to earn this badge')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='loyalty/badges/')),
                ('points_reward', models.PositiveIntegerField(default=0, help_text='Bonus loyalty points awarded when this badge is unlocked.')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['badge_type', 'threshold'],
            },
        ),
        migrations.CreateModel(
            name='LoyaltyReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('reward_type', models.CharField(choices=[('discount', 'Discount'), ('free_class', 'Free Class'), ('product', 'Product'), ('service', 'Service'), ('custom', 'Custom')], default='custom', max_length=20)),
                ('points_cost', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('stock', models.PositiveIntegerField(blank=True, help_text='Leave blank for unlimited stock.', null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='loyalty/rewards/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['points_cost', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LoyaltyRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('checkin', 'Check-in'), ('class_attended', 'Class Attended'), ('referral', 'Referral'), ('workout_logged', 'Workout Logged'), ('intake_completed', 'Intake Completed'), ('birthday', 'Birthday'), ('product_purchase', 'Product Purchase'), ('custom', 'Custom')], max_length=30, unique=True)),
                ('points', models.PositiveIntegerField(default=0)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('max_per_day', models.PositiveIntegerField(blank=True, help_text='Cap how many times this rule can fire per member per day. Leave blank for unlimited.', null=True)),
            ],
            options={
                'ordering': ['action'],
            },
        ),
        migrations.CreateModel(
            name='LoyaltyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(help_text='Positive = credit, negative = debit')),
                ('transaction_type', models.CharField(choices=[('earn', 'Earned'), ('redeem', 'Redeemed'), ('expire', 'Expired'), ('adjust', 'Manual Adjustment')], default='earn', max_length=10)),
                ('action', models.CharField(blank=True, choices=[('checkin', 'Check-in'), ('class_attended', 'Class Attended'), ('referral', 'Referral'), ('workout_logged', 'Workout Logged'), ('intake_completed', 'Intake Completed'), ('birthday', 'Birthday'), ('product_purchase', 'Product Purchase'), ('custom', 'Custom'), ('redeem', 'Redemption'), ('adjust', 'Adjustment')], max_length=30)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loyalty_transactions_created', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_transactions', to='members.memberprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MemberBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='members.memberprofile')),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earned_by', to='loyalty.badgemilestone')),
            ],
            options={
                'ordering': ['-earned_at'],
                'unique_together': {('member', 'milestone')},
            },
        ),
    ]
