# Generated by Django 5.1.9 on 2026-03-25 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GymProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gym_name', models.CharField(max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('primary_color', models.CharField(default='#1a1a2e', max_length=7)),
                ('accent_color', models.CharField(default='#e94560', max_length=7)),
                ('tagline', models.CharField(blank=True, max_length=300)),
                ('about_text', models.TextField(blank=True)),
                ('welcome_message', models.TextField(blank=True)),
                ('homepage_layout', models.CharField(default='hero', max_length=50)),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='banners/')),
                ('social_instagram', models.URLField(blank=True)),
                ('social_facebook', models.URLField(blank=True)),
                ('social_tiktok', models.URLField(blank=True)),
                ('social_youtube', models.URLField(blank=True)),
                ('custom_domain', models.CharField(blank=True, max_length=200)),
                ('custom_domain_active', models.BooleanField(default=False)),
                ('waiver_text', models.TextField(blank=True)),
                ('email_signature', models.TextField(blank=True)),
                ('features_enabled', models.JSONField(default=dict)),
                ('landing_page_active', models.BooleanField(default=True)),
                ('landing_page_sections', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Gym Profile',
                'verbose_name_plural': 'Gym Profile',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('timezone', models.CharField(default='America/New_York', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_custom', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LocationHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fri', 'Friday'), ('sat', 'Saturday'), ('sun', 'Sunday')], max_length=3)),
                ('open_time', models.TimeField(blank=True, null=True)),
                ('close_time', models.TimeField(blank=True, null=True)),
                ('is_closed', models.BooleanField(default=False)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hours', to='core.location')),
            ],
            options={
                'verbose_name': 'Location Hours',
                'verbose_name_plural': 'Location Hours',
                'ordering': ['location', 'day'],
                'unique_together': {('location', 'day')},
            },
        ),
    ]
