# Generated by Django 5.1.9 on 2026-03-25 02:04

import django.db.models.deletion
import django_tenants.postgresql_backend.base
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('platform_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GymTenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name])),
                ('gym_name', models.CharField(max_length=200)),
                ('owner_email', models.EmailField(max_length=254)),
                ('trial_start_date', models.DateTimeField(auto_now_add=True)),
                ('trial_active', models.BooleanField(default=True)),
                ('subscription_status', models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled')], db_index=True, default='trial', max_length=20)),
                ('member_app_active', models.BooleanField(default=False)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=100)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=100)),
                ('data_retention_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenants', to='platform_admin.plan')),
            ],
            options={
                'verbose_name': 'Gym Tenant',
                'verbose_name_plural': 'Gym Tenants',
            },
        ),
        migrations.CreateModel(
            name='GymDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('is_primary', models.BooleanField(db_index=True, default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='tenants.gymtenant')),
            ],
            options={
                'verbose_name': 'Gym Domain',
                'verbose_name_plural': 'Gym Domains',
            },
        ),
    ]
