# Generated by Django 5.1.9 on 2026-03-25 02:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('core', '0001_initial'),
        ('members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_in_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('checked_out_at', models.DateTimeField(blank=True, null=True)),
                ('method', models.CharField(choices=[('rfid', 'RFID Card'), ('kiosk', 'Kiosk'), ('manual', 'Manual'), ('app', 'App')], max_length=20)),
                ('is_guest', models.BooleanField(default=False)),
                ('checked_in_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_checkins', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='core.location')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='members.memberprofile')),
            ],
            options={
                'verbose_name': 'Check-In',
                'verbose_name_plural': 'Check-Ins',
                'ordering': ['-checked_in_at'],
            },
        ),
        migrations.CreateModel(
            name='DoorDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('device_type', models.CharField(choices=[('entrance', 'Main Entrance'), ('exit', 'Exit'), ('studio', 'Class Studio'), ('locker', 'Locker Bank'), ('pos', 'Point of Sale'), ('kiosk', 'Self-Service Kiosk')], max_length=20)),
                ('device_token', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='core.location')),
            ],
            options={
                'verbose_name': 'Door Device',
                'verbose_name_plural': 'Door Devices',
                'ordering': ['location', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LockerAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locker_number', models.CharField(max_length=20)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locker_assignments', to='core.location')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locker_assignments', to='members.memberprofile')),
            ],
            options={
                'verbose_name': 'Locker Assignment',
                'verbose_name_plural': 'Locker Assignments',
                'ordering': ['location', 'locker_number'],
            },
        ),
        migrations.CreateModel(
            name='MemberCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfid_token', models.CharField(max_length=100, unique=True)),
                ('card_number', models.CharField(max_length=20, unique=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('deactivation_reason', models.CharField(blank=True, max_length=100)),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_cards', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='members.memberprofile')),
            ],
            options={
                'verbose_name': 'Member Card',
                'verbose_name_plural': 'Member Cards',
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='CardScanLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanned_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('result', models.CharField(choices=[('granted', 'Access Granted'), ('denied_inactive', 'Denied — Inactive Membership'), ('denied_payment', 'Denied — Payment Overdue'), ('denied_suspended', 'Denied — Account Suspended'), ('denied_hours', 'Denied — Outside Access Hours'), ('denied_unknown', 'Denied — Card Not Recognised')], db_index=True, max_length=30)),
                ('scan_type', models.CharField(choices=[('entry', 'Entry'), ('exit', 'Exit'), ('studio', 'Class Studio'), ('locker', 'Locker'), ('purchase', 'Purchase'), ('kiosk', 'Kiosk Check-In'), ('login', 'App Login')], max_length=20)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_logs', to='checkin.doordevice')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_logs', to='checkin.membercard')),
            ],
            options={
                'verbose_name': 'Card Scan Log',
                'verbose_name_plural': 'Card Scan Logs',
                'ordering': ['-scanned_at'],
            },
        ),
        migrations.CreateModel(
            name='MemberNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('visibility', models.CharField(choices=[('staff', 'All Staff'), ('manager', 'Manager+'), ('owner', 'Owner Only')], default='staff', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_notes', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='members.memberprofile')),
            ],
            options={
                'verbose_name': 'Member Note',
                'verbose_name_plural': 'Member Notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('attended', models.BooleanField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='core.location')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Shift',
                'verbose_name_plural': 'Shifts',
                'ordering': ['-date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='StaffRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('add', 'Add Staff'), ('remove', 'Remove Staff')], max_length=20)),
                ('target_email', models.EmailField(blank=True, max_length=254)),
                ('role', models.CharField(max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_requests', to='core.location')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff Request',
                'verbose_name_plural': 'Staff Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('area', models.CharField(max_length=100)),
                ('priority', models.IntegerField(default=1)),
                ('shift_type', models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening'), ('all', 'All Shifts')], max_length=20)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_templates', to='core.location')),
            ],
            options={
                'verbose_name': 'Task Template',
                'verbose_name_plural': 'Task Templates',
                'ordering': ['location', 'shift_type', 'priority'],
            },
        ),
        migrations.CreateModel(
            name='CleaningTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_date', models.DateField(db_index=True)),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('verification_photo', models.ImageField(blank=True, null=True, upload_to='cleaning/')),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cleaning_tasks', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='checkin.tasktemplate')),
            ],
            options={
                'verbose_name': 'Cleaning Task',
                'verbose_name_plural': 'Cleaning Tasks',
                'ordering': ['-shift_date', 'template__priority'],
            },
        ),
        migrations.CreateModel(
            name='TrainerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('specialties', models.CharField(blank=True, max_length=300)),
                ('certifications', models.CharField(blank=True, max_length=300)),
                ('is_visible_to_members', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trainer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trainer Profile',
                'verbose_name_plural': 'Trainer Profiles',
            },
        ),
        migrations.CreateModel(
            name='AccessRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_start_time', models.TimeField(blank=True, null=True)),
                ('access_end_time', models.TimeField(blank=True, null=True)),
                ('days_allowed', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_rules', to='core.location')),
                ('membership_tier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_rules', to='billing.membershiptier')),
            ],
            options={
                'verbose_name': 'Access Rule',
                'verbose_name_plural': 'Access Rules',
                'unique_together': {('membership_tier', 'location')},
            },
        ),
        migrations.CreateModel(
            name='ClientAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_type', models.CharField(choices=[('trainer', 'Trainer'), ('nutritionist', 'Nutritionist')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_assignments', to='members.memberprofile')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client Assignment',
                'verbose_name_plural': 'Client Assignments',
                'ordering': ['-start_date'],
                'unique_together': {('staff', 'member', 'assignment_type')},
            },
        ),
    ]
