# Generated by Django 5.1.9 on 2026-03-25 02:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AISystemPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_type', models.CharField(choices=[('member_coach', 'Member AI Coach'), ('owner_assistant', 'Owner AI Assistant')], db_index=True, max_length=30, unique=True)),
                ('base_content', models.TextField()),
                ('gym_additional_context', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI System Prompt',
                'verbose_name_plural': 'AI System Prompts',
            },
        ),
        migrations.CreateModel(
            name='MemberAIAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('plateau', 'Plateau Detected'), ('inactivity', 'Inactivity'), ('concern', 'Health Concern')], db_index=True, max_length=50)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(db_index=True, default=False)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_alerts', to='members.memberprofile')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_ai_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Member AI Alert',
                'verbose_name_plural': 'Member AI Alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MemberAIConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_message_at', models.DateTimeField(auto_now=True)),
                ('conversation_history', models.JSONField(default=list)),
                ('session_type', models.CharField(choices=[('general', 'General'), ('workout', 'Workout'), ('nutrition', 'Nutrition'), ('intake', 'Health Intake')], db_index=True, default='general', max_length=30)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversations', to='members.memberprofile')),
            ],
            options={
                'verbose_name': 'Member AI Conversation',
                'verbose_name_plural': 'Member AI Conversations',
                'ordering': ['-last_message_at'],
            },
        ),
        migrations.CreateModel(
            name='OwnerAIConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_message_at', models.DateTimeField(auto_now=True)),
                ('conversation_history', models.JSONField(default=list)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_ai_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Owner AI Conversation',
                'verbose_name_plural': 'Owner AI Conversations',
                'ordering': ['-last_message_at'],
            },
        ),
    ]
