# Generated by Django 5.1.9 on 2026-03-25 02:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('paid', 'Paid')], default='draft', max_length=10)),
                ('summary', models.JSONField(default=dict, help_text='Keyed by staff_id. Each entry: {"name": "...", "hours": 40, "classes": 12, "total": 850.00}')),
                ('total_payout', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_payroll_periods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-period_end'],
            },
        ),
        migrations.CreateModel(
            name='StaffPayRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_type', models.CharField(choices=[('hourly', 'Hourly'), ('salary', 'Salary'), ('per_class', 'Per Class'), ('commission', 'Commission')], default='hourly', max_length=15)),
                ('rate', models.DecimalField(decimal_places=2, help_text='Hourly rate, annual salary, per-class fee, or commission %.', max_digits=8)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('location', models.ForeignKey(blank=True, help_text='Leave blank to apply across all locations.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pay_rates', to='core.location')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pay_rates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-effective_from'],
            },
        ),
    ]
